[package]
name = "check_http_ng"
version = "0.3.0"
authors = ["Marvin Lee Fimmel <kontakt@ekranos.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
futures.workspace = true
nagiosplugin.workspace = true
reqwest.workspace = true
tokio = { workspace = true, features = ["full"] }
