[package]
name = "check_http_ng"
version = "0.2.1"
authors = ["Marvin Lee Fimmel <kontakt@ekranos.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
futures = "0.3.14"
nagiosplugin = "0.4"
reqwest = "0.11.1"
structopt = "0.3.21"
tokio = { version = "1.2.0", features = ["full"] }
